### ISSUE TITLE
Support for FT232H

### ISSUE THREAD

**Issue by ardnew** [l29ah/libmpsse#18]
This is one of the more recent/popular chips from FTDI, with breakouts offered by Adafruit and Sparkfun. It has a single MPSSE channel on a USB high-speed interface.

I couldn't find any documentation explicitly saying if this chip was supported or not (and the App Note in docs appears to have been written prior its release). From a cursory glance, the pin definitions in `mpsse.h` looked possibly incompatible, but I'm not sure what else to be suspicious of.

Has anyone tried this chip? Would it be a substantial effort to add support?

**Comment by ardnew** [comment]
I am working on a Go module for this chip (https://github.com/ardnew/ft232h), but the `D2XX`+`LibMPSSE` drivers it currently uses are a bit of a headache.

I would be interested in moving over to `libftdi` and this library, and I feel confident I could add support (for the C code only) if it isn't presently available. Would like confirmation from a current developer.

**Comment by l29ah** [comment]
I'm mostly using libmpsse on ft2232h.

**Comment by ardnew** [comment]
@l29ah the FT232H and FT2232H are two different devices, in case you thought I was meaning FT2232H (I wasn't 😄)

**Comment by l29ah** [comment]
Ouch, i've misread your post :)

I've used libmpsse on both. I suspect ft4232h will also work.
