### ISSUE TITLE
Missing build tool and odd errors.

### ISSUE THREAD

**Issue by hetii** [l29ah/libmpsse#5]
Hi there...

I have trouble to run this library.
At the first point there is no configure executable file that check configuration and prepare all necessary file to use make.

Even when I use `configure` from devttys0 fork and compile library for python2 or 3 I got errors like this:

	m = MPSSE(SPI0, ONE_MHZ, MSB)
	m.Start()

	 m.Write(b"\x01\x00\x00\xff\x02\xfe\xd4\x02*\x00")
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-10-5a9895f60b9d> in <module>()
	----> 1 m.Write(b"\x01\x00\x00\xff\x02\xfe\xd4\x02*\x00")

	/usr/src/libmpsse/src/mpsse.py in Write(self, data)
	    248                 Raises an exception on failure.
	    249 		"""
	--> 250                 if _mpsse.Write(self.context, data) == MPSSE_FAIL:
	    251                         raise Exception(self.ErrorString())
	    252                 return MPSSE_OK

	TypeError: Write() takes exactly 3 arguments (2 given)

	In [11]: m.Write(b"\x01\x00\x00\xff\x02\xfe\xd4\x02*\x00",1)
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-11-77ab47853def> in <module>()
	----> 1 m.Write(b"\x01\x00\x00\xff\x02\xfe\xd4\x02*\x00",1)

	TypeError: Write() takes 2 positional arguments but 3 were given

**Comment by l29ah** [comment]
Consider reading `docs/INSTALL`.

**Comment by l29ah** [comment]
After you've built it properly, check whether reverting 148b0702c30f8ed29ddd962bb920185d36bb9a48 fixes the behaviour for you. I don't have an MPSSE device handy.
